

GET http://localhost:7000/items/5eac7ba432c76bca3234f983

###

GET http://localhost:7000/items


###
POST http://localhost:7000/items/create HTTP/1.1
content-type: application/json

{
    "item":{
        "name": "misalPav58",
        "price": 25,
        "description": "Tikhat"        
    }
}


###
POST http://localhost:7000/items/create HTTP/1.1
content-type: application/json

{
    "item":{
        "name": "misalPav",
        "price": 25,
        "description": "Tikhat"
    }
}